apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-generator
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/clementtrecourt/homelab-stack.git
        revision: feat/observability-slo

        directories:
          - path: kubernetes/apps/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/clementtrecourt/homelab-stack.git
        targetRevision: feat/observability-slo
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
