apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    # On dit à Traefik d'utiliser l'entrypoint web (port 80) car le tunnel arrive en HTTP
    traefik.ingress.kubernetes.io/router.entrypoints: web
resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 128Mi
spec:
  ingressClassName: traefik
  rules:
  - host: argocd.clem-ops.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http # On utilise le port 80 d'ArgoCD