apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgAoYmU/J6n5DaDN+9oAl+qigFHXtxYv5MneeotZ1szIt/2s5bAkmEHKYP/idyJ4c3PBKo3PM2RG8AKU/zc4J/u/R/ulqudR/eVfTO1ovXjF+6cvRMlA3H4ALnNiFebnUbhAQCu0isdtQXn7XVOyfTILP9nJzrMwfUQqP+YJuKdJYpTMJ68CA+hrK05yGrqfZUuLHnr4NGs17xsGWSX42KWyrbBhwr8z/jJkzohdO4Xlw7rXtXA4wcaCuStyA/tTd2HntrzRVfyWijprgVzaF0P6wwyqGNXtc+LgeI6Hcl6Vt0MlY5LPIiQg1o3EfLwUUEdp/NzfwWS9k2dhES+XeJlktTiG0AZZ69W5SO5tdpEwBlBz76jR1ZzqlXGuOs7tMUqS0qFZWuf7imoSNdN6WKMqpg3bOznppo7dkYyi28nytnbUST80jKhG8sJt9trh1UuWVnjo92OEn595JmGhXJOcgrmrPQAxjq7/IETM8jw23andbvNiFw2H+Nu8S9jLPfYRvlytW34tfkpWRKuZD/3vixxzWTRsgrq0U0sPLDI9ZgbDLXTQA8n+c3JuKKmVHWI9UOjBTt28tneJ7DgW94WFK4HsV5dmq+dFC8U7nV/Sc4kmITzj181C67h8b2QTxaMhXyoxyWRp+4YZXv3G2FzERRmCJuV1LoW1b2TEGlTRABJlgkuvQYYaT69Q5M0CjNb6FlFdsv0FCczR4K0JFhGsASv0VQKfKnrdcFPMk7jiiUBnbQbCnEhqB5ehgrAM6L8KCDDEc9fwTZk7TSc=
  template:
    metadata:
      creationTimestamp: null
      name: argocd-secret
      namespace: argocd
    type: Opaque

