{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-tunnel-token",
    "namespace": "kube-system",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-tunnel-token",
        "namespace": "kube-system",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "token": "AgB3gtTIgavx1PmWzaMZmRDZrtAYltFnl1vVt7audODnCMWpQQFv5gquZobIFT3nv1293/A7uq4dIIdkwFiIAbnLj0mMYtYYDoQNyw70c2U5AuI3RJPaezCdhJ/DZVJ8mkENxIypgkFECjFFJDnd7xhSehESgFi+rEnKpQfavGi3bOM9Lz0JqjDveocQN6SHlh3PzKzBP4rrYvJMc9CsZDNgadHTrUt6tY7ClOFD4GmvYAUI8Lt9cBBE93tsUBeMk4gEzef4vmFXC/ZxroGnU7s4QiaiQp5hEagWpmkc94uUJzmxT4D541buzM7upIIVtNAO/1eTaoOtdaKQVBqOA/Ms80jDPzNTgMwwlcCOveDQ00/AK4YjTeY/BY23XyAVuTtNCLH+rv5zJafpMLiG44nB1T+9n/NckUEsS5jxEZeR1uQQJc64JBW3DbjESg+lD4dndzeJhkxzNMP8LoVv+NmXbyxwr7l1n3IYNFn9T1FcOXMBKSaL5t9SrC+FEENzDMpd78oQ+Cy0/MRLg6tr1MPWPulQVh2sGG5Xf55XrItGyKp4GjSdg242gGSLeLNNrzLl9EbwkbFoftOYDbjZeG4+oKHlcgKyquIc+Tu14j6DkCxu+meayjRy9UrXFxBplI4Dydfwq2gH2MRPn7F6jezVqqXiLztbaM0jdqMzOLSo2WhsKlCCwQFcRpQLOa79ntIK4DccVCzXw0AXZumRzLEjAiOnuyUUoywT7Vw0jyOJ3JRZRRqnldWnqe1J+qfQHAjAoTR3yPIi2wLYOreX9TsZnDtGgJU6rUMvjn1KhYXt9IU0yUFrAv7/6+/pchPD6Ps9CjYd0/M6+z2G1hRBOq7JCrj0CsMqn+KFBO5GS03HyxgmF8Tj9pRokb9nNAUYffTD5I95wu1LndMmztLuha88ydx8A5i/5qAxU4vorQfhcLJeD1fILZgE"
    }
  }
}
