{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "cert-manager",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "cert-manager",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "api-token": "AgAL2loL8/0sR0cHXgbV6cPEOcg+s+v7Ao8VHoGFqsKoC4a/erSRI9Tq/g7sTWIIGcqcGw1YTnyRgR0yTsU4r7fCtdZ22/T+JNfUynmloZXPA1YTKm7VyzQjO3ju70jV7Dtpv6wPEzNtKUiWjgOhD5qVxVTInHezuYrH4hogy2hCYvN6tFdJe4lhG4SxVCGxPGWZV1Cseg01yfu12shoqeKIaKAgP0tX7QRN7lppWT3udR41KbPScFddYxr7ewVhcDHk8to/tNNBahOLH3nu0x5v4ObLXNDQA63b0nUxz6WibLBIGlLBjp/uMliQvv54yGGtOZIUH4z8/USZgc6zoGOrabgrjXDCnd5ql/paVwZC7iAAkFLT/PjtLDyRK3g7oGRwdBFRovccMq3DuviKbtIvvxZEaYREzDyUDZMp3X5PXQIkyucTgZ83yJSm7rrIQhNGvTnf66XYYQMtJNzozqUYg1PuZYwTp4L9Rq49BQ6jq9hxC4cUK5KUvhsngwmGh+AlKPzsM1X6MuUw0OYys/GqumnM4SjLGmPBk6DMeQLgo6jbP2qYdtW/PLQJnbeJPs/pUtoHYGIZzmHNGgSgmFaS6EA2WTmGyYu1bwWC7hAkyJSyDUS6/4FagKcuqZ15y1H2B4x3Jatc9/KQOqH/E8ruD3GSJtLCPRDdvJ01NUg64g/hB4YmQ0u5tk9mdgAhLSsrTPkSmyhOzep70ArLDQDbEfis6Jr5ITEyLoKv0noK/0wbSrtRsAe1"
    }
  }
}
