apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketbase-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketbase
spec:
  selector:
    matchLabels:
      app: pocketbase
  replicas: 1 
  template:
    metadata:
      labels:
        app: pocketbase
    spec:
      containers:
        - name: pocketbase
          image: ghcr.io/muchobien/pocketbase:latest 
          args: ["serve", "--http=0.0.0.0:8090", "--dir=/pb_data"]
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: data
              mountPath: /pb_data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pocketbase-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pocketbase
spec:
  ports:
    - port: 80
      targetPort: 8090
  selector:
    app: pocketbase
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pocketbase-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: api.clem-ops.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pocketbase
                port:
                  number: 80