apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    
    logs:
      general:
        level: INFO
      access:
        enabled: true
        format: json

    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: true

    ports:
      web:
        port: 8000
        expose: true
        exposedPort: 80
      
      
      websecure:
        port: 8443
        expose: true
        exposedPort: 443
        http3:
          enabled: true
        tls:
          enabled: true

    tlsOptions:
      default:
        minVersion: VersionTLS13
        sniStrict: false # On laisse false pour éviter les soucis avec Cloudflare

    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 128Mi
      path: /data

    ingressRoute:
      dashboard:
        enabled: false