apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-cloudflare-r2
  namespace: velero
spec:
  encryptedData:
    cloud: AgCNAxDwsOMFU+sfE7NcS9lBpoHHvdljtqD9jzQ03SgcpLVZXY4AugLU/4FiKrLa+A8k5VU3hgnUKk+e8Ujflv75aLmaqWg4J67nP1Bztx1zIwgjt0qjlYf8iXx0VNhbHXM+Q9A4hYdfNm0Z4d1EzkNEvEpOwXSrFhUQ5Gmj30ZA1DSfld2BYMvpFakgkoObzkBJ7VeVvm8RP+jS1PL0kVjSEB94gprBa6ZGpPzw6HAIAOo3md9LT7kUtZ+dPLQl8udKwxtTW+8GSNZ+h/t/t86sp4FqsKJvrpHloJK9XC+semSHsypAShtYYkBGr+AZrA2dbFfYzmwrecs07vm2A2tSi841s5bA7CPf9h9632tukGij4nVeC/CZaAYp7kI7oD2lOmHpuEvP+NlfHkxxdaMHLD0GisRNdvWDltcjUwDUiwCVj3CGmIR5EAiRa8T3rZEeJeI6JjEpklfCob3gxthE3fE2tChOECdNCG6/wPrf/Ljm8e44HJG/s3KSQeo+Ao0We0mmkIifS/mEF++2Wya2XBBLIi7TmxoPXkusYrMbIlmphL0AmNLpVw077Hh9kkjVJjysKE3kNAOY2i/F/n9AFYeozmgFwNortlj7djr8iJrJKIzr22M+gP2lgyQPmMQ3ac+4dtci2m3DmMMv4P1YHTE6MbZftKUUc/bgMBIn1e1+BtKnCymfd0uc2/XOmfoPUw+dQRMU/zDhqh1dI7XKZIjT8n8JJQnFjN5CrWGhwz4UnZKJNMY5t53CGloTtW7cZnYOvP3vdA0RLj5wmb3OvjdDoic99bGpcCc70rRk1qCGtEaT0V5B+GN6eb5W/gABdlnfsO3igdU642rhFpuJ3JI2QaJgwcQspxdYTeHUSUfW81Y6/iOMPUnk7Iu8+2/cNc1GIJVcng==
  template:
    metadata:
      creationTimestamp: null
      name: velero-cloudflare-r2
      namespace: velero

