apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCpRDCWBzPvJe+wrSi9D8blApFdDeRmk8PVmaKwZHIYBmPMKYgN275ZXD+1q334y84qHg4k/7nQ2GDK6uKEsnHTBmE7/5aKJlYz0f7cyB8L+KKFCXxiGM/umZLQjSDR1lkI3/86r7XHsBb86sMFL7erkOcQsrR7Trh24Smbu1J3IQ6vrTD6yp6YZeZqMu8Qo6mmkBLtXPBM8d4A4gdfH7GY0W450F8qLpppsq3I04nwjW+/5JSOZuuottSqNoBzQ/8Y7y5HZ9hgQvYmFH6vlCr+RnFrfQlGU5mCif2igta/VxzhVin2Y6hYmLnJTYUNP3ZGT6DudrLijPNbauGZXnPIcb1v4WFrkuGkzeo3FwlKxV7gkgKtMHa2tzloAvQtStXmKn5QiJd8698RzV3ZDZkLHQatr7FZIM7xyZdjMajDdfX45FAO63NaMuVH9c753huXNJFwP1IG2Xwap19pb0Q/Q+DgTnaAiQsfY7lEVyja3lf1k6Bj0saPjho3Gel8s90KfJBbCtbYWgr+5QJijZ8ScmJvK9v0/F/g7QI91b8mONo2UhQeiF9r1xvg2Pam72vDXfOB5wngx5qcLNTqNM4LLfFDLjRUH7e9nMdTWrocWIoHgvhCdPD7dkijcwVm2PIHwDXJMwKUP2fZuxdHva10VjWX3Y3SPtwlZyIsVT55TdmExKE7Uwb+cCDnJqerlK7IPnamESGdWxaorTHGW8HLkujELmltA1Uc+X+abEaByZMHy697MCKKpkkg0Y88ctynBYMjGlsmp45JvipuR8iikXzIRF0P9FNUlZmTUl+NRlYjGbNnYSoBUU0ymvWcm4v2bcT3Hn6bbBaB9lswAm3b01U/UAesRAYhhad7kIaPItjKAwYtl11oDgauu9/jEIW2Qq/5cbnvig==
  template:
    metadata:
      creationTimestamp: null
      name: velero-credentials
      namespace: velero

