apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 5.3.0
    helm:
      values: |
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.6.0
            volumeMounts:
              - mountPath: /target
                name: plugins

        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: k3s-velero-backups
              config:
                region: us-east-1
                s3ForcePathStyle: true
                s3Url: https://06b18dd79d4024c8265b6e86ca0762b5.r2.cloudflarestorage.com

        credentials:
          useSecret: true
          name: velero-credentials

        deployNodeAgent: true
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
