apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBwcwyRfslJojmvIK7wLbuXbZGUMMQzVfbmnDOlfBhgkHlMp0UaMXT6utQKcixaRn78zmiHhxs/sv6gWl+xFrniBc2SlOx6SSgbX1jDVA/6RFI6z28S+n1LhWGLcMzpQEuWF5HMaVjhp3bBaaltXcWrgTnLmxDVadN5cEhgzmopMCxn9xNS7Qqt2EyW5pneWJPcvn9kirDKrDVLhWW2rHmEfhq0h7drCgQa/9c4C1BR1GN+Lqt5gcPxf5oip9ShOW/3cxLoiWRFaz7jlD3a3s7k7J5xchsqEfIp5715V84IQMpoSoXBV7N3+FH7olA6KJheewLRn8cH1r6VErxBgRJtINg6ilCkr30GknZug0aiXja4N8YZUoUYvKlk/pDoXAs2f/5SaJ7ueZKxhhIgd5NS0D0NrKsQDY8l/ezQn8Au9xGE+8VVky5Hab2CjtJNk3Cwm1S+kKowoxpLShaplwG42Dgv/6wCUA4gb6zSkqg/epTufbC3rbseO48PW1OlGm3aOd5Ygbb3e63aIDD5WF7cuI/bWRrcrVq7OBEzicMbg7R2Uxch/Ke5xvy6QBxRkvxH5Spxy5uWn7vwrMveKI667qwXYds0/Mo2hAR+Nu7SpdvcJwG61HYBlfXtzzvP1eHcA05rxcG8gow8r53sOelXN8WZLGUqWHXqhfEox2vs4+r1gnfCw1jplcvF3Zpdgj3RYaVGk0GXgVBUq5BLNp55PdKleJWaOXqkd9VSn9H2XXhdmyjbyvHW9jMKmhGux+BF9sWHp9qf524D6zRDOsqEYHTdvD8Gk+fQD1iat65VSMoxUZGaKvTe59FG2gNpGlJ8QUrK5vLre7IhsES3SfBmrR+DE6uyORKWyiBsMaAuLTaZ47+7VW21ElGlLLT3It9IwOWjtWk7Fw==
  template:
    metadata:
      creationTimestamp: null
      name: velero-credentials
      namespace: velero

