---
- name: Mise à jour du cache apt et upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  register: apt_upgrade_result

- name: Reboot si nécessaire après upgrade
  ansible.builtin.reboot:
    reboot_timeout: 120
    connect_timeout: 10
    post_reboot_delay: 15
  when: apt_upgrade_result.changed

- name: Installation des paquets de base
  ansible.builtin.apt:
    name:
      - curl
      - ufw
      - python3-pip
      - htop
      - unattended-upgrades
      - open-iscsi
    state: present

- name: Désactivation de la SWAP (requis par K3s)
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Suppression de la SWAP du fichier fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'

- name: Hardening Kernel (Sysctl)
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_items:
    - { key: "net.ipv4.ip_forward", value: "1" }
    - { key: "net.ipv4.conf.all.accept_redirects", value: "0" }
    - { key: "net.ipv4.conf.all.send_redirects", value: "0" }
    - { key: "net.ipv4.conf.all.rp_filter", value: "1" }
    - { key: "net.ipv6.conf.all.disable_ipv6", value: "0" }

- name: Configuration de UFW (Firewall)
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: any
  with_items:
    - "22"
    - "6443"
    - "53"
    - "8472"
    - "10250"
    - "9100"
    - "80"
    - "443"

- name: Activation de UFW
  community.general.ufw:
    state: enabled
    policy: deny
