apiVersion: v1
kind: Namespace
metadata:
  name: pocketbase
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketbase-pvc
  namespace: pocketbase
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketbase
  namespace: pocketbase
spec:
  selector:
    matchLabels:
      app: pocketbase
  replicas: 1 
  template:
    metadata:
      labels:
        app: pocketbase
    spec:
      containers:
        - name: pocketbase
          image: ghcr.io/muchobien/pocketbase:0.22
          args: ["serve", "--http=0.0.0.0:8090", "--dir=/pb_data"]
          ports:
            - containerPort: 8090
 
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: data
              mountPath: /pb_data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pocketbase-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pocketbase
  namespace: pocketbase
spec:
  ports:
    - port: 80
      targetPort: 8090
  selector:
    app: pocketbase
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: force-https-headers
  namespace: pocketbase
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pocketbase-route
  namespace: pocketbase
spec:
  entryPoints:
    - web 
  routes:
    - match: Host(`api.clem-ops.org`)
      kind: Rule
      services:
        - name: pocketbase
          port: 80
      middlewares:
        - name: force-https-headers