apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgANrW5SeAV0hzhPPX1Aq9zfIVqVhMZzXep9ZyplUNp0PiljBYogyYpmF0vs8HLjKZp3QQQSUp1mXRuyQb1r7oHRXL2RS2T5bTfrGpsxQ9I++ki/pVQF9iZUY3GCsAYwLbFLyCfl1sCrV2fuRI4LYqN993xb2CAaDAsA6c2SJs2Yy5uvEytQpu1YoBKlVjwCB/a70AICNjdAdRxTpxPhTkiJfUYXd6plyOjLMdP/YgP1qUHpwrkqT/GJaR2qYAT8A12Ul/PXTuTD1tpI9+COxXYAbVIkz8VjENBfQYyhe6+XGqX6+noJWpyj4vtq7cSSliCsKUSGeMi52Ypx0h3jmSHw/UpInqpIsRLpaWxg8t2yAwCEakGX6C6TL5SC5VGgiSlQb/MXxG1voHRZ4L7RIE2SMWjjOQzHY3uqiN5FAJQ/dSfk7JUtwBK1mZLnCaENOpqN5PfOo+/p8qiKRJgWwIJEmhjP6X5SUBBNJU+9gPn+E8F0JROf0AHfRC/dsrC5gNFL6uwYCa3bMPD6PUeET2kLvSEblL0UuXEI4Z2gCJWwhfDNF5GdbHNA6cfvD/8osuBSMApSQUx1kYz73Ci3awwAKQr8z9093q4ga3h9xbbGw960lkKf39w1tpAhEVUH4AW8QSpsiiJqatMHkNXgUeWCfk5SqYXG4Tc1GQJuahvZItoEmTdXwCk5rnlg6K9ZRfPl77e/1uh82a0tyBZSK9504WYRzL2oxJARu+mIUSRxQCRQ0D4ODC+ww6E71pYxvnuZ6022MejtHeGLghWNG5ifYTV1NXQTrLgsTdVQHHHTS41o4WkacIsvmVuP2oGP3VNSvAOHFWkbMA/dExF4qQuP9Vcrtcq7yKpaKWFbaooFhWVLBuqMi5T2RVuDtBovtP/7l4JLPf9BVA==
  template:
    metadata:
      creationTimestamp: null
      name: velero-credentials
      namespace: velero

