---
- name: Vérifier si K3s est déjà installé
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Télécharger et installer K3s sur le Master
  shell: |
    curl -sfL https://get.k3s.io | sh -s - server \
    --write-kubeconfig-mode 644 \
    --node-name {{ inventory_hostname }} \
    --tls-san {{ ansible_host }}
  when: not k3s_installed.stat.exists

- name: Attendre que le node-token soit généré
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Lire le token du Master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token_encoded

- name: Définir le token en tant que fact pour les workers
  set_fact:
    k3s_token: "{{ node_token_encoded.content | b64decode | trim }}"