---
- name: Vérifier si K3s est déjà installé
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Télécharger et installer K3s sur le Worker
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['k3s-master']['ansible_host'] }}:6443 \
    K3S_TOKEN={{ hostvars['k3s-master']['k3s_token'] }} sh -s - agent \
    --node-name {{ inventory_hostname }}
  when: not k3s_installed.stat.exists