{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "immich-postgres-user",
    "namespace": "immich",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "immich-postgres-user",
        "namespace": "immich",
        "creationTimestamp": null
      },
      "type": "kubernetes.io/basic-auth"
    },
    "encryptedData": {
      "password": "AgCEHrNitSuX1SdJxxqd66wFagELdv+H1WgFXfBz+R1OLSVIJuPHLwYbs8Bo5LdFK/gQyZvcUKeil1jVGJkE6xvm0xQ65D5fYnyi/Qe5V46+4/OCmpX8pa4Ywt/OO4n10ObMd56di2auZ+sBmBgV4oPk3TvaMZ+rYRQVq2c9VME3odbZZErlH6880sWgmqldxKGWJ9jk8DIf3i5qxgYHdstIL8ueFkNdQjY6cT2vOYwXYz3rQDAAtoO8hf4g1jZpNnUwO/bNfCHZ4tWhKxAnXnWsYAp+wjqLOLnLvGHmeKJ2uYYP0dm29ms+TEJAzC2rKZbRlzCr97GgJvYFZ2YcF30iEidQPgkz+n4DB+0tkjtt8MvAwmkNEbYUl0zzMrzs4X8twkXq2Nzm35X4eNSHedpFKjvtHjvTeYba5p3peeHpaLFzl+ckPE8uG2s7MGrZuVmjo08jtIMXN2FOdal0JgNQgAtiinJoWZapDEivzg05c5NxFS7QoYNLjag/C4sSo9erepfd+7/ZDZceeSBarCOtWMuOWfvYghkWGp2bkZ/DcqL01k0eaSQK8XhrOuq1eMFjouaRulGoktMIWOSmCa72soiaf0B5ZDsZLnGKU7yJpGaFnUvn8QgymMkKcIti/DKoNel4wW/9y9g/PLthMYyJjXVrGqPoPjL3YK/44lwJJeghxuWlWKb7tTSxzyaI3DDNSnfb",
      "username": "AgDB1Wa5RSBn/sYXvISTfT9kqIsiU+GGa61t4pr/e/bULQaeCl+F0u9AExWXnot8TfVd2+iNgVxyrI5JkeB0tkYIenAzuGgs9t4z6zk2AQYpevgOZ3fOiEib79ep5H49xRVX6ofM5DsaGleqY4crUrq/0c2a91rEjL9LtoHQpZt3IoxTj7lq/6laYHIuYmzoiNCt2drYgBMtScf+LeFSQZ9laTGEwGIq5l+YjNgDEKCZCr8NaMrpLUDe2Uy+nDRmo74UeI+LBPOvWoxfuRU0GgO0Cby+LLle9GwHvYkq8r4crLbBcNO/eMgl+cIGIBVkbz1NB0waHII1fBlrqs1svhfekpQOJf47rCV7Tk9PK9BDF1AOtGcKKoN08AUmWjooyhTVH2wjbv6jivsNupR2yZiAwEXWgWXH1FCyuPNmF9I3Ae7OjakcO0B4rQSNwgfL2gMHaUVDv5VM8LbqRCF5857tEu8JThWEnbOzRM5IV92IRLphkmjPA63oNIg42QMIvAWfolizIrpFykIDm5PhfnMKOvoTWmFyXVcol3o2saO/z5F9ThWdLpMmpJrrpuh/QHG3scDtI1DlPKNbhG5JY5+jfs2yG9Rg8mWZ3W0iDPoukZ0wfM0GrUswz321fXgSoZK6hxoLisLwba7WM4AqWYxw/RbEt5wa8gDye2lRHj2K0LdZr81k+NQlaceuGs7m4D9d8Zvp97o="
    }
  }
}
