---
- name: Ensure the sudo group is present
  ansible.builtin.group:
    name: sudo
    state: present

- name: Create the 'clem' user
  ansible.builtin.user:
    name: clem
    comment: "Clem Administrator Account"
    shell: /bin/bash
    groups: sudo
    append: true
    create_home: true
    state: present
    password: "{{ user_clem_password | password_hash('sha512') }}"

- name: Allow 'clem' to run sudo without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
