apiVersion: apps/v1
kind: Deployment
metadata:
  name: directus
  namespace: backend-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directus
  template:
    metadata:
      labels:
        app: directus
    spec:
      containers:
      - name: directus
        image: directus/directus:11
        ports:
        - containerPort: 8055
        env:
        - name: KEY
          value: "67984812-7067-4f51-8404-367610065091"
        - name: SECRET
          value: "d9e843e1-3f62-4a00-9830-749666014521"
        - name: ADMIN_EMAIL
          value: "admin@clem-ops.org"
        - name: ADMIN_PASSWORD
          value: "MonSuperMotDePasse"
        - name: DB_CLIENT
          value: "pg"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "tracker_db"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "MonSuperMotDePasse"
        - name: PUBLIC_URL
          value: "https://api.clem-ops.org"
         
        - name: REFRESH_TOKEN_COOKIE_SECURE
          value: "true"
        - name: REFRESH_TOKEN_COOKIE_SAME_SITE
          value: "none"
        - name: REFRESH_TOKEN_COOKIE_DOMAIN
          value: "clem-ops.org"
        
 
        - name: CORS_ENABLED
          value: "true"
        - name: CORS_ORIGIN
          value: "true"
        - name: CORS_METHODS
          value: "GET,POST,PATCH,DELETE,OPTIONS"

        - name: CORS_ALLOWED_HEADERS
          value: "Content-Type,Authorization,X-Directus-Project,X-Requested-With"
        - name: CORS_CREDENTIALS
          value: "true"
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: directus
  namespace: backend-stack
spec:
  ports:
  - port: 80
    targetPort: 8055
  selector:
    app: directus