apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-etcd
  template:
    metadata:
      labels:
        app: dns-etcd
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        runAsNonRoot: true
      containers:
        - name: etcd
          image: registry.k8s.io/etcd:3.5.6-0
          command:
            - etcd
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://0.0.0.0:2379
            - --data-dir=/etcd-data
          ports:
            - containerPort: 2379
              name: client
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: etcd-ram-storage
              mountPath: /etcd-data
          resources: # Consomme ~35Mo de RAM
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "30m"
              memory: "64Mi"
      volumes:
        - name: etcd-ram-storage
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: dns-etcd
spec:
  ports:
    - port: 2379
      targetPort: 2379
  selector:
    app: dns-etcd
