---
- name: Créer le dossier de configuration K3s
  file:
    path: /etc/rancher/k3s
    state: directory

- name: Déposer la configuration K3s Worker
  template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml

- name: Installer K3s sur le Worker
  shell: curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ hostvars[groups['k3s_master'][0]]['k3s_token'] }} sh -